FROM hub.iflytek.com/xfyun_webdev/webserver/java:v3
FROM java:openjdk-8u111-apline

LABEL maintainer="mqgao <mqgao@ilytek.com>"

EXPOSE  12012

COPY backend/xfyun-platform-aphrodite-service/target/xfyun-platform-aphrodite-service.jar /app/